---
version: 2
plan:
  project-key: MOON
  key: ROCKET
  name: Build the rocket
stages:
  - Build hull:
    - Build

Build:
  tasks:
    - script:
      - echo 'Hello World!'
---
version: 2
plan:
  project-key: MOON
  key: ROCKET
  name: Build the rockets

# List of plan's stages and jobs
stages:
  - Build the rocket stage:
    - Build

#Job definition
Build:
  tasks:
    - script:
        - mkdir -p falcon/red
        - echo wings > falcon/red/wings
        - sleep 1
        - echo 'Built it'
    - test-parser:
        type: junit
        test-results: '**/junit/*.xml' 
  # Job's requirements
  requirements:
     - isRocketFuel
  # Job's artifacts. Artifacts are shared by default.
  artifacts:
     - name: Red rocket built
       pattern: falcon/red/wings
