version: 2
plan:
  project-key: MARS
  key: SPACESHIP008
  name: My SPACESHIP008

stages:
  - Stage 1:
      jobs:
        - Job 1
  - Stage 2:
      jobs:
        - Job 2
  - Stage 3:
      jobs:
        - Job 3      
  - Stage 4:
      jobs:
        - Job 4     
Job 1:
  tasks:
    - script:
        - echo 'Hello WORLD from YAML Specs Job 11'
Job 2:
  tasks:
    - script:
        - echo 'Hello WORLD from YAML Specs Job 22'
Job 3:
  tasks:
    - script:
        - echo 'Hello WORLD from YAML Specs Job 33'
Job 4:
  tasks:
    - script:
        - echo 'Hello WORLD from YAML Specs Job 44'        
---
version: 2
deployment:
  name: Deployment Project
  source-plan: MARS-SPACESHIP008
release-naming:
  next-version-name: Deployment-${bamboo.buildNumber}
  applies-to-branches: false
environments:
  - QA
  - Staging
QA:
  tasks:
    - script:
        interpreter: /bin/sh
        scripts:
          - echo "123"
  final-tasks:
    - clean


Staging:
  tasks:
    - script:
        interpreter: /bin/sh
        scripts:
          - echo "123"
  final-tasks:
    - clean
---
version: 2
deployment:
  name: Deployment Project
  source-plan: MARS-SPACESHIP008
deployment-permissions:
  - users:
      - auser
    permissions:
      - view
default-environment-permissions:
  - users:
      - auser
    groups:
      - bamboo-dc
    permissions:
      - view
      - edit
      - deploy
