version: 2
plan:
  project-key: MARS
  key: ROCKET
  name: My Plan-1

stages:
  - Stage 1:
      jobs:
        - Job 1
  - Stage 2:
      jobs:
        - Job 2
  - Stage 3:
      jobs:
        - Job 3      
  - Stage 4:
      jobs:
        - Job 4     
Job 1:
  tasks:
    - script:
        - echo 'Hello WORLD from YAML Specs Job 1'
Job 2:
  tasks:
    - script:
        - echo 'Hello WORLD from YAML Specs Job 2'
Job 3:
  tasks:
    - script:
        - echo 'Hello WORLD from YAML Specs Job 3'
Job 4:
  tasks:
    - script:
        - echo 'Hello WORLD from YAML Specs Job 4'        
---
version: 2
deployment:
  name: MARS
  source-plan: MARS-ROCKET
release-naming:
  next-version-name: release-1
  applies-to-branches: false
  auto-increment: true
environments:
- DEV
- QA
DEV:
  tasks:
  - clean
  - script:
      interpreter: SHELL
      scripts:
      - echo "Deploy"
  final-tasks: []
  variables: {}
  requirements: []
  notifications: []
QA:
  tasks:
  - clean
  - script:
      interpreter: SHELL
      scripts:
      - echo "deploy2"
  final-tasks: []
  variables: {}
  requirements: []
  notifications: []
---
version: 2
deployment:
  name: MARS
deployment-permissions:
- roles:
  - logged-in
  - anonymous
  permissions:
  - view
- users:
  - azure
  permissions:
  - view
  - edit
  - viewConfiguration
environment-permissions:
- DEV:
  - roles:
    - logged-in
    - anonymous
    permissions:
    - view
  - users:
    - azure
    permissions:
    - view
    - edit
    - deploy
    - viewConfiguration
- QA:
  - roles:
    - logged-in
    - anonymous
    permissions:
    - view
  - users:
    - azure
    permissions:
    - view
    - edit
    - deploy
    - viewConfiguration
