apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build

on:
  push:
    branches:
      - '**'

jobs:
  java-build:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1